# Generated by Django 4.1.7 on 2023-04-04 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_rename_alboms_song_albums'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='albums',
            new_name='alboms',
        ),
    ]
