# Generated by Django 4.1.7 on 2023-04-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_rename_albums_song_alboms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='alboms',
        ),
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='song',
            name='audio',
            field=models.FileField(default='default_audio.mp3', upload_to='song_audio/'),
        ),
        migrations.AddField(
            model_name='song',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='song',
            name='photo',
            field=models.ImageField(upload_to='song_photos/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
