# Generated by Django 4.1.7 on 2023-04-05 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_alter_concert_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='news_photos/')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Новости',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.AlterModelOptions(
            name='concert',
            options={'verbose_name': 'Концерты', 'verbose_name_plural': 'Концерты'},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'verbose_name': 'Музыка', 'verbose_name_plural': 'Музыка'},
        ),
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='song',
            name='audio',
            field=models.FileField(upload_to='song_audio/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='photo',
            field=models.ImageField(blank=True, upload_to='song_photos/'),
        ),
    ]
