# Generated by Django 4.1.7 on 2023-04-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_news_alter_concert_options_alter_song_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.CharField(max_length=200, verbose_name='Альбом'),
        ),
        migrations.AlterField(
            model_name='song',
            name='audio',
            field=models.FileField(upload_to='song_audio/', verbose_name='Аудио'),
        ),
        migrations.AlterField(
            model_name='song',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='На главном'),
        ),
        migrations.AlterField(
            model_name='song',
            name='photo',
            field=models.ImageField(blank=True, upload_to='song_photos/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
    ]
