# Generated by Django 4.1.7 on 2023-04-05 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_alter_song_album_alter_song_audio_alter_song_is_main_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concert',
            name='title',
        ),
        migrations.AddField(
            model_name='concert',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='concert',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='concert',
            name='location',
            field=models.CharField(default='', max_length=200, verbose_name='Место'),
        ),
        migrations.AddField(
            model_name='concert',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='concert',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='На главном'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='photo',
            field=models.ImageField(blank=True, upload_to='concert_photos/', verbose_name='Фото'),
        ),
    ]
