# Generated by Django 4.1.7 on 2023-04-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_alter_merchandise_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandise',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
