# Generated by Django 4.1.7 on 2023-04-07 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_sweatshirt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trinkets',
            fields=[
                ('merchandise_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webapp.merchandise')),
                ('type', models.CharField(max_length=20, verbose_name='Тип')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.merchandisecategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Разное',
                'verbose_name_plural': 'Разное',
            },
            bases=('webapp.merchandise',),
        ),
    ]
