# Generated by Django 4.1.7 on 2023-07-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandise',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
